import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ShopItems from './shopItems'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Health Tips</title>
        <meta name="description" content="Generated by Muhammad Nasir" />
        <link rel="icon" href="/images/LN2.png" />
      </Head>
      <ShopItems />
      
    </div>
  )
}
